FROM golang:1.24-alpine AS builder

WORKDIR /app/app-service

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o app-service ./cmd/main.go

FROM alpine:latest

RUN adduser -D appuser

WORKDIR /app

COPY --from=builder /app/app-service .

EXPOSE 3001

USER appuser

ENTRYPOINT ["./app-service"]
