FROM golang:1.24-alpine AS builder

WORKDIR /app/search-service

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o search-service ./cmd/main.go

FROM alpine:latest

RUN adduser -D appuser

WORKDIR /app
COPY --from=builder /app/search-service/search-service .

EXPOSE 4000

USER appuser

ENTRYPOINT ["./search-service"]
